version: '3'
services:
  app:
    container_name: react-app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 3900DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
