import { PrismaClient } from "@prisma/client";
import ItemController from "../controllers/item-controller";
import UserController from "../controllers/user-controller";
const prisma = new PrismaClient();

const USERS: {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    id: string | null; // generated by prisma
}[] = [
    {
        firstName: "Ender",
        lastName: "Man",
        email: "admin@endermen.com",
        password: "123456",
        id: null,
    },
    {
        firstName: "Jamie",
        lastName: "Foster",
        email: "jf@endermen.com",
        password: "123456",
        id: null,
    },
];

const ITEMS: {
    title?: string;
    url: string;
    description?: string;
    thumbnail?: string;
    type?: string;
    siteName?: string;
    collectionName?: string;
    tagNames?: string[];
    exclude?: boolean;
    userEmail?: string;
}[] = [
    {
        title: "Competitive programming with AlphaCode",
        url: "https://www.deepmind.com/blog/competitive-programming-with-alphacode",
        description:
            "Solving novel problems and setting a new milestone in competitive programming.",
        thumbnail:
            "https://assets-global.website-files.com/621e749a546b7592125f38ed/6221e6c759f19819bd5bec04_CodeGen.jpg",
        type: "article",
        siteName: "deepmind.com",
        collectionName: "Programming",
        tagNames: ["DeepMind"],
    },
    {
        title: "Writing WebSocket client applications - Web APIs | MDN",
        url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications",
        description:
            "WebSocket client applications use the WebSocket API to communicate with WebSocket servers using the WebSocket protocol.",
        thumbnail:
            "https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png",
        type: "article",
        siteName: "developer.mozilla.org",
        collectionName: "Web",
        tagNames: ["WebSockets", "Opensource"],
        exclude: true,
    },
    {
        title: "Just-In-Time: The Next Generation of Tailwind CSS - Tailwind CSS",
        url: "https://tailwindcss.com/blog/just-in-time-the-next-generation-of-tailwind-css",
        description:
            "One of the hardest constraints we've had to deal with as we've improved Tailwind CSS over the years is the generated file size in development. Today I'm super excited to share a new project that makes this constraint a thing of the past: a just-in-time compiler for Tailwind CSS.",
        thumbnail:
            "https://tailwindcss.com/_next/static/media/card.79a37188.jpg",
        type: "article",
        siteName: "tailwindcss.com",
        collectionName: "Frontend",
        tagNames: ["Tailwind"],
        exclude: true,
    },
    {
        title: "Meta bets big on AI with custom chips -- and a supercomputer",
        url: "https://techcrunch.com/2023/05/18/meta-bets-big-on-ai-with-custom-chips-and-a-supercomputer/",
        description:
            "Meta wants the world -- and particularly investors -- to know it's going big or going home where it concerns AI and the hardware to build it.",
        thumbnail:
            "https://techcrunch.com/wp-content/uploads/2021/11/facebook-meta-twist.jpg?resize=1200,675",
        type: "article",
        siteName: "TechCrunch",
        collectionName: "Microchip",
        tagNames: ["Meta"],
        exclude: true,
    },
    {
        title: "Twitter's Recommendation Algorithm",
        url: "https://blog.twitter.com/engineering/en_us/topics/open-source/2023/twitter-recommendation-algorithm",
        description:
            "Twitter aims to deliver you the best of what’s happening in the world right now. This blog is an introduction to how the algorithm selects Tweets for your timeline.",
        thumbnail:
            "https://cdn.cms-twdigitalassets.com/content/dam/blog-twitter/engineering/en_us/main-template-assets/Eng_EXPLORE_Pink.png.twimg.768.png",
        type: "article",
        siteName: "blog.twitter.com",
        collectionName: "Programming",
        tagNames: ["Twitter"],
        exclude: true,
    },
    {
        title: "Ten Years of TypeScript",
        url: "https://devblogs.microsoft.com/typescript/ten-years-of-typescript/",
        description:
            "Today is TypeScript’s birthday! But this birthday is a special one – 10 years ago today, on October 1st, 2012, TypeScript was unveiled publicly for the first time. The Early Days When TypeScript first debuted, there was a lot of skepticism –",
        thumbnail:
            "https://devblogs.microsoft.com/typescript/wp-content/uploads/sites/11/2018/08/typescriptfeature.png",
        type: "article",
        siteName: "TypeScript",
        collectionName: "Programming",
        tagNames: ["TypeScript"],
        exclude: true,
    },
    {
        url: "https://www.apple.com/au/newsroom/2023/06/introducing-apple-vision-pro/",
        collectionName: "VR",
        tagNames: ["vr", "Apple"],
        exclude: true,
    },
    {
        url: "https://blog.google/technology/ai/google-palm-2-ai-large-language-model/",
        collectionName: "LLM",
        tagNames: ["Google", "LLM"],
        exclude: true,
    },
    {
        url: "https://developer.chrome.com/blog/whats-new-css-ui-2023/",
        collectionName: "Frontend",
        tagNames: ["CSS"],
        exclude: true,
    },
    {
        url: "https://www.nasa.gov/feature/goddard/2022/nasa-s-webb-takes-star-filled-portrait-of-pillars-of-creation",
        collectionName: "Space",
        tagNames: ["JWT"],
    },
    {
        url: "https://exoplanets.nasa.gov/news/1761/beginnings-life-on-our-world-and-others/",
        collectionName: "Space",
        tagNames: ["NASA", "exoplanets"],
    },
    {
        url: "https://www.quantamagazine.org/an-enormous-gravity-hum-moves-through-the-universe-20230628/",
        collectionName: "Space",
        tagNames: ["gravity", "pulsars"],
    },
    {
        url: "https://www.astronomy.com/science/nessie-nebula-shows-how-shocks-can-birth-new-stars/",
        collectionName: "Space",
        tagNames: ["nebulae", "stars"],
        userEmail: USERS[1].email,
    },
    {
        url: "https://www.quantamagazine.org/the-sum-product-problem-shows-how-addition-and-multiplication-constrain-each-other-20190206/",
        collectionName: "Mathematics",
        tagNames: ["conjecture"],
        userEmail: USERS[1].email,
    },
    {
        url: "https://www.sciencenews.org/article/viking-age-ancient-solar-flare-trade-archaeology",
        collectionName: "Space",
        tagNames: ["archaelogy"],
        userEmail: USERS[1].email,
        exclude: true,
    },
    {
        url: "https://www.quantamagazine.org/are-there-reasons-to-believe-in-a-multiverse-20230517/",
        collectionName: "Space",
        tagNames: ["multiverse"],
        userEmail: USERS[1].email,
    },
    {
        url: "https://www.sciencefocus.com/future-technology/a-guide-to-mesh-networks/",
        collectionName: "Technology",
        tagNames: ["networks", "wifi"],
        userEmail: USERS[1].email,
    },
];

async function main() {
    for await (const user of USERS) {
        try {
            await UserController.createUser(
                user.firstName,
                user.lastName,
                user.email,
                user.password,
            );
            const userInfo = await UserController.userInfoByEmail(user.email);

            user.id = userInfo.id;
            console.log(
                `Created user ${user.email} with password ${user.password}, new id: ${userInfo.id}`,
            );
        } catch (e) {
            if (e instanceof Error) {
                console.log(`${e.message}... email: ${user.email}`);
            }
        }
    }

    if (USERS.length > 0) {
        const defaultUserId = USERS[0].id;
        console.log(USERS);

        console.log(`defaultUserId: ${defaultUserId}`);

        for await (const item of ITEMS.filter((item) => !item.exclude)) {
            const idx = USERS.findIndex(
                (user) => user.email === item.userEmail,
            ); // -1 if not found
            const userId = USERS[idx]?.id ?? defaultUserId;

            if (userId) {
                await ItemController.createItem(
                    userId,
                    item.url,
                    item.collectionName ?? "Default",
                    item.tagNames ?? [],
                    true,
                );
                console.log(`Created new item for user ${userId}`);
            } else {
                console.log(`User not found for item ${item.url}`);
            }
        }
    } else {
        console.log("No users created, skipping item creation");
    }
}
main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
